### PR TITLE
Reloaded : "Toggle rendering of FX chain on mixing sources" , has tog…

### PR DESCRIPTION
**Pull request by d-j-a-y**
…glebutton

### CODE REVIEW

**Comment by c0ntrol** [comment]
incomplete patch; the toggle button must match its state in veejay (hence why it is just a button now, carrying no state info)

**Comment by d-j-a-y** [comment]
> the toggle button must match its state in veejay (hence why it is just a button now, carrying no state info)

??? you mean that the buttom be toggled accordingly to event from veejay / vims ?

**Comment by c0ntrol** [comment]
yes, it should toggle depending on the information in the status line

**Comment by c0ntrol** [comment]
after update sources, you could add to update_globalinfo in vj-api.c:
<pre>
if( info->status_tokens[SUBRENDER] != history[SUBRENDER] ) {
  // update button
}
</pre>

when mode is MODE_STREAM or MODE_SAMPLE

**Comment by d-j-a-y** [comment]
>yes, it should toggle depending on the information in the status line (not on send/receive vims message)
[...]
>after update sources, you could add to update_globalinfo in vj-api.c:

ok will do that later.

**Comment by c0ntrol** [comment]
taking this issue, more updates to reloaded coming

**Pull request merged**
