### PR TITLE
libvje / refactor : function calls done !

### PR DESCRIPTION
**Pull request by d-j-a-y**
* w,h
* clean headers

**+** 
* overclock : remove inline blur and blur2 : duplicated with common.c 
* cutstop : add missing licence
* flare : rename A,B --> frame , frame2
* averageblend : remove average_blend_applyN from internal.h (unused)

#78

### CODE REVIEW

**Comment by d-j-a-y** [comment]
_refactor all function calls_ : **done** ! 

+
headers cleaned `#include "common.h"` 
Nota : transition/*.c need `#include <libvje/effects/common.h>` , something wired in makefile? (that i don't have found...)

**Comment by c0ntrol** [comment]
Hi, nice job! Just two remarks

Please do not use frame->len inside the loop but instead assign it to a local variable

and ...

It should be const int len instead of const unsigned int len, since len field on VJFrame is also just an int. 

Accepting pull when frame->len inside loop is resolved :)

**Comment by d-j-a-y** [comment]
>Accepting pull when frame->len inside loop is resolved :)
I feel a scripting mood ;-)

**Comment by d-j-a-y** [comment]
Yo ... !
[back to the grill again](https://www.youtube.com/watch?v=3XB7BXeGy3k)...

**Comment by d-j-a-y** [comment]
@c0ntrol !!! 

Seems to have runtime effect with veejay_memset !
```
....
E: Found Gremlins in your system.
W: No fresh ale found in the fridge.
I: Running with sub-atomic precision...
E: /usr/lib/libveejay-1.5.so.0(veejay_print_backtrace+0x2e) [0x7f401e7ee4b0]
E: veejay() [0x403a55]
E: /lib/x86_64-linux-gnu/libc.so.6(+0x352f0) [0x7f401e37a2f0]
E: /usr/lib/libveejay-1.5.so.0(veejay_memset+0) [0x7f401eb51488]
E: Bugs compromised the system.
```
Gdb backtrace : 
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b60488 in veejay_memset () from /usr/lib/libveejay-1.5.so.0
(gdb) backtrace
#0  0x00007ffff7b60488 in veejay_memset () from /usr/lib/libveejay-1.5.so.0
#1  0x00007ffff7801bb4 in vj_effect_initialize (width=720, height=576, full_range=1) at vj-effect.c:548
#2  0x00007ffff77c2d6a in veejay_init (info=0x651000, x=-1, y=-1, arg=0x0, def_tags=0, gen_tags=0) at liblavplayvj.c:1880
#3  0x0000000000404083 in main (argc=2, argv=0x7fffffffdeb8) at veejay.c:854

```

i'm trying to explore / isolate guilty commit.
4d7a20f995efa <---- ok

3c99dcad1bd5 <--- ko

**Comment by d-j-a-y** [comment]
After have rebuilded again an again , more or less commit by commit  ... now everything back to the normal tracks .... 

rarely wired strange.... !

**Comment by d-j-a-y** [comment]
>Seems to have runtime effect with veejay_memset !

And again this morning !!!! 

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b60bc8 in veejay_memset () from /usr/lib/libveejay-1.5.so.0
1: veejay_memset = (void *(*)(void *, uint8_t, size_t)) 0x7ffff7801e79 <fast_memset>
(gdb) backtrace
#0  0x00007ffff7b60bc8 in veejay_memset () from /usr/lib/libveejay-1.5.so.0
#1  0x00007ffff7804fad in vj_effect_initialize (width=800, height=600, full_range=1)
    at vj-effect.c:548
#2  0x00007ffff77ca0fd in veejay_init (info=0x650f80, x=-1, y=-1, arg=0x0, def_tags=0, 
    gen_tags=0) at liblavplayvj.c:1880
#3  0x0000000000404060 in main (argc=2, argv=0x7fffffffdeb8) at veejay.c:854

(gdb) disassemble 
Dump of assembler code for function veejay_memset:
=> 0x00007ffff7b60bc8 <+0>:	jns    0x7ffff7b60be8 <yuyv_mmreg_+8>
   0x00007ffff7b60bca <+2>:	xor    $0xff,%bh
   0x00007ffff7b60bcd <+5>:	jg     0x7ffff7b60bcf <veejay_memset+7>
   0x00007ffff7b60bcf <+7>:	add    %ch,-0x87fd7(%rbx)
End of assembler dump.

(gdb) backtrace
#0  0x00007ffff7b60bc8 in veejay_memset () from /usr/lib/libveejay-1.5.so.0
#1  0x00007ffff7804fad in vj_effect_initialize (width=800, height=600, full_range=1)
    at vj-effect.c:548
#2  0x00007ffff77ca0fd in veejay_init (info=0x650f80, x=-1, y=-1, arg=0x0, def_tags=0, 
    gen_tags=0) at liblavplayvj.c:1880
#3  0x0000000000404060 in main (argc=2, argv=0x7fffffffdeb8) at veejay.c:854
```

**Comment by nelburg** [comment]
probably, something was changed in one of the effects; Look at the method that returns the vj_effect struct. I'll have a look later today

**Comment by c0ntrol** [comment]
there was a compile warning; fixed that by including vjmem.h in vj-effect

**Comment by d-j-a-y** [comment]
>there was a compile warning; fixed that by including vjmem.h in vj-effect

OUch !!! well done !

**Pull request merged**
