### PR TITLE
Enchancement : "Sequencer Clear All"

### PR DESCRIPTION
**Pull request by d-j-a-y**
* Button in ui (on_button_seq_clearall) right to activate sequencer checkbox
* Callback clear entire grid (VIMS_SEQUENCE_DEL)
* sequencer col and row has #define
* new vj_gui_t struct members :  sequencer_col & sequencer_row

### CODE REVIEW

**Comment by c0ntrol** [comment]
Hi, can you instead of 
````
for (slot = 0; slot < info->sequencer_col * info->sequencer_row ; slot++)
 	{
 		multi_vims( VIMS_SEQUENCE_DEL, "%d", slot );
````

do something like
````
if( seq_it == -1) {
  for( slot = 0; slot < MAX_SEQUENCES; slot ++ ) {
		v->seq->samples[ seq_it ].sample_id = 0;
		v->seq->samples[ seq_it ].type = 0;
  }
}
```` 

in veejay-server/vj-event.c: vj_event_sequencer_del_sample

doing it in the UI might fill the VIMS message queue (its a flood of at most 100 messages)

**Comment by d-j-a-y** [comment]
@c0ntrol wrote :

>  do something like ....

I cp mainly from reloaded/vp-api.c/load_sequence_list  , the code you pasted come from veejay-server , and the `struct veejay_t` is not in reloaded from what i saw.

So N+1 VIMS are sent now ... way better than always MAX_SEQUENCES ;-)

**Comment by c0ntrol** [comment]
Hi, I changed VIMS 342 (VIMS_SEQUENCE_DEL) so that the first argument can be '-1' to delete all samples from the sequencer. So, it can now be just a single message to clear them all

**Comment by d-j-a-y** [comment]
Enchancement / "Sequencer Clear All" (VIMS_SEQUENCE_DEL -1)

**Pull request merged**
