### PR TITLE
libvje minor fixes

### PR DESCRIPTION
**Pull request by d-j-a-y**
* #133 
* #132

### CODE REVIEW

**Comment by nelburg** [comment]
Hi, some things:

d50e79b: remove break after return statement in switch, remove default case and simply return default function pointer at end of function
5436753: no unrolling of loops, if auto vectorization fails to optimize these plain c routines other things should be changed
7fe498b:  +1 for divide by zero, but please assign pixel_Y_hi_ instead of 0xff. same for < 16 comparisons, that should be pixel_Y_lo for Y channel, or 16-240 for UV. 
d0174bf: also no unrolling of loops
537a35d: +1 (but i saw this one already?)

**Comment by nelburg** [comment]
same for < 16 comparisons, that should be pixel_Y_lo for Y channel, or 16-240 for UV.  

That was wrong, must be 0; clamping to UV range should be done after pixel value calculation, not before

**Comment by d-j-a-y** [comment]
> That was wrong, must be 0; clamping to UV range should be done after pixel value calculation, not b
before 

???
I have changed some '16' by  pixel_Y_lo of foo_Y functions ... i did change nothing for bar_C functions.

> (but i saw this one already?)

The average calculation was in did already pushed, but not used.

**Comment by nelburg** [comment]
I fixed it in common.c ; In short, before the new pixel value is calculated, both inputs need to have a sane value (to prevent divide by zero) and after the pixel value is calculated, it should be clamped into a valid range

**Pull request merged**
